# Generated by Django 6.0.1 on 2026-02-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_author_user_alter_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('layout_structure', models.JSONField(default=list)),
            ],
        ),
    ]
