# Generated by Django 6.0.2 on 2026-02-08 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_initial'),
        ('content', '0001_initial'),
        ('home', '0001_initial'),
        ('media_app', '0001_initial'),
        ('navigation', '0001_initial'),
        ('setup', '0002_author_user_alter_author_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='author', name='avatar'),
                migrations.RemoveField(model_name='author', name='managed_categories'),
                migrations.RemoveField(model_name='author', name='role'),
                migrations.RemoveField(model_name='author', name='user'),
                migrations.RemoveField(model_name='post', name='author'),
                migrations.RemoveField(model_name='post', name='categories'),
                migrations.RemoveField(model_name='homesectionitem', name='section'),
                migrations.RemoveField(model_name='homesectionitem', name='post'),
                migrations.RemoveField(model_name='post', name='cover_image'),
                migrations.RemoveField(model_name='menuitem', name='menu'),
                migrations.RemoveField(model_name='menuitem', name='parent'),
                migrations.RemoveField(model_name='post', name='status'),
                migrations.RemoveField(model_name='post', name='tags'),
                migrations.DeleteModel(name='Redirect'),
                migrations.DeleteModel(name='Role'),
                migrations.DeleteModel(name='Author'),
                migrations.DeleteModel(name='Category'),
                migrations.DeleteModel(name='HomeSection'),
                migrations.DeleteModel(name='HomeSectionItem'),
                migrations.DeleteModel(name='Media'),
                migrations.DeleteModel(name='Menu'),
                migrations.DeleteModel(name='MenuItem'),
                migrations.DeleteModel(name='Status'),
                migrations.DeleteModel(name='Post'),
                migrations.DeleteModel(name='Tag'),
            ],
            database_operations=[],
        )
    ]
