# Generated by Django 6.0.2 on 2026-02-08 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('media_app', '0001_initial'),
        ('setup', '0002_author_user_alter_author_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Role',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('name', models.CharField(max_length=50, unique=True)),
                        ('slug', models.SlugField(unique=True)),
                        ('description', models.TextField(blank=True)),
                    ],
                    options={
                        'verbose_name': 'Cargo',
                        'verbose_name_plural': 'Cargos',
                        'db_table': 'role',
                    },
                ),
                migrations.CreateModel(
                    name='Author',
                    fields=[
                        (
                            'id',
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ('keycloak_id', models.UUIDField(blank=True, null=True, unique=True)),
                        ('name', models.CharField(max_length=150)),
                        ('bio', models.TextField(blank=True, null=True)),
                        (
                            'avatar',
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='author_avatars',
                                to='media_app.media',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'author',
                        'ordering': ['name'],
                    },
                ),
            ],
            database_operations=[],
        )
    ]
