# Generated by Django 6.0.2 on 2026-02-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('setup', '0002_author_user_alter_author_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='HomeSection',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('title', models.CharField(max_length=100)),
                        ('section_type', models.CharField(max_length=50)),
                        ('order', models.IntegerField()),
                        ('is_active', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'home_section',
                        'ordering': ['order'],
                    },
                ),
                migrations.CreateModel(
                    name='HomeSectionItem',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('order', models.IntegerField()),
                        (
                            'post',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='content.post',
                            ),
                        ),
                        (
                            'section',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='home.homesection',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'home_section_item',
                        'ordering': ['order'],
                    },
                ),
            ],
            database_operations=[],
        )
    ]
