# Generated by Django 6.0.2 on 2026-02-08 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0005_alter_category_options_alter_post_options_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['order'], 'verbose_name_plural': 'Secoes da Home'},
        ),
        migrations.AlterModelOptions(
            name='homesectionitem',
            options={'ordering': ['order'], 'verbose_name_plural': 'Itens da Home'},
        ),
        migrations.AlterField(
            model_name='homesection',
            name='section_type',
            field=models.CharField(
                choices=[
                    ('CAROUSEL', 'Carrossel'),
                    ('HIGHLIGHTS', 'Destaques'),
                    ('GRID', 'Grade'),
                    ('LIST', 'Lista'),
                    ('SIDEBAR', 'Barra lateral'),
                ],
                default='HIGHLIGHTS',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='post',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='section_appearances',
                to='content.post',
            ),
        ),
        migrations.AlterField(
            model_name='homesectionitem',
            name='section',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='items',
                to='home.homesection',
            ),
        ),
        migrations.AddConstraint(
            model_name='homesectionitem',
            constraint=models.UniqueConstraint(
                fields=('section', 'post'), name='unique_home_section_post'
            ),
        ),
        migrations.AddConstraint(
            model_name='homesectionitem',
            constraint=models.UniqueConstraint(
                fields=('section', 'order'), name='unique_home_section_order'
            ),
        ),
    ]
