# Generated by Django 6.0.2 on 2026-02-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_homesection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['order'], 'verbose_name_plural': 'Seções da Home'},
        ),
    ]
