# Generated by Django 6.0.2 on 2026-02-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [('setup', '0002_author_user_alter_author_id')]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Media',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('file', models.FileField(upload_to='media/')),
                        ('title', models.CharField(max_length=200)),
                        ('alt_text', models.CharField(blank=True, max_length=150, null=True)),
                        ('image_type', models.CharField(max_length=50)),
                        ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'media',
                        'ordering': ['-uploaded_at'],
                    },
                )
            ],
            database_operations=[],
        )
    ]
