# Generated by Django 6.0.2 on 2026-02-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('media_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'Midias'},
        ),
        migrations.AlterField(
            model_name='media',
            name='image_type',
            field=models.CharField(
                choices=[
                    ('IMAGE', 'Imagem'),
                    ('VIDEO', 'Video'),
                    ('AUDIO', 'Audio'),
                    ('DOCUMENT', 'Documento'),
                ],
                default='IMAGE',
                max_length=50,
            ),
        ),
    ]
