# Generated by Django 6.0.2 on 2026-02-09 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('media_app', '0002_alter_media_options_alter_media_image_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'Mídias'},
        ),
    ]
