# Generated by Django 6.0.2 on 2026-02-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('media_app', '0001_initial'),
        ('setup', '0002_author_user_alter_author_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Category',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('name', models.CharField(max_length=100)),
                        ('slug', models.SlugField(max_length=100, unique=True)),
                        ('color', models.CharField(max_length=7, null=True)),
                        ('is_active', models.BooleanField(default=False)),
                    ],
                    options={
                        'db_table': 'category',
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='Status',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('name', models.CharField(max_length=100)),
                    ],
                    options={
                        'db_table': 'status',
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='Tag',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('name', models.CharField(max_length=100)),
                        ('slug', models.SlugField(max_length=100, unique=True)),
                    ],
                    options={
                        'db_table': 'tag',
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='Post',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('title', models.CharField(max_length=200)),
                        ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                        ('slug', models.SlugField(max_length=100, unique=True)),
                        ('content', models.TextField()),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        (
                            'author',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='accounts.author',
                            ),
                        ),
                        ('categories', models.ManyToManyField(to='content.category')),
                        (
                            'cover_image',
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name='posts_using_image',
                                to='media_app.media',
                            ),
                        ),
                        (
                            'status',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                to='content.status',
                            ),
                        ),
                        ('tags', models.ManyToManyField(blank=True, to='content.tag')),
                    ],
                    options={
                        'db_table': 'post',
                        'ordering': ['-id'],
                    },
                ),
            ],
            database_operations=[],
        )
    ]
