# Generated by Django 6.0.2 on 2026-02-08 17:53

from django.db import migrations


def forward_copy_status_fk_to_status_choice(apps, schema_editor):
    Post = apps.get_model('content', 'Post')
    for post in Post.objects.select_related('status').all():
        if post.status_id:
            post.status_choice = post.status.name
            post.save(update_fields=['status_choice'])


def reverse_copy_status_fk_to_status_choice(apps, schema_editor):
    Post = apps.get_model('content', 'Post')
    Status = apps.get_model('content', 'Status')

    status_map = {status.name: status.id for status in Status.objects.all()}
    for post in Post.objects.all():
        status_id = status_map.get(post.status_choice)
        if status_id:
            post.status_id = status_id
            post.save(update_fields=['status'])


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0002_add_post_status_choice'),
    ]

    operations = [
        migrations.RunPython(
            forward_copy_status_fk_to_status_choice,
            reverse_copy_status_fk_to_status_choice,
        ),
    ]
