# Generated by Django 6.0.2 on 2026-02-08 17:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('content', '0003_copy_status_fk_to_status_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='status_choice',
            new_name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
