# Generated by Django 6.0.2 on 2026-03-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_alter_author_options_alter_author_name'),
        ('content', '0006_alter_category_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Rascunho'),
                    ('REVIEW', 'Em revisão'),
                    ('PUBLISHED', 'Publicado'),
                    ('ARCHIVED', 'Arquivado'),
                ],
                default='DRAFT',
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name='PostStatusTransition',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'from_status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Rascunho'),
                            ('REVIEW', 'Em revisão'),
                            ('PUBLISHED', 'Publicado'),
                            ('ARCHIVED', 'Arquivado'),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    'to_status',
                    models.CharField(
                        choices=[
                            ('DRAFT', 'Rascunho'),
                            ('REVIEW', 'Em revisão'),
                            ('PUBLISHED', 'Publicado'),
                            ('ARCHIVED', 'Arquivado'),
                        ],
                        max_length=20,
                    ),
                ),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_at_snapshot', models.DateTimeField(blank=True, null=True)),
                (
                    'actor_role',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='post_status_transitions',
                        to='accounts.role',
                    ),
                ),
                (
                    'changed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='post_status_transitions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'post',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='status_transitions',
                        to='content.post',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Transição de status do post',
                'verbose_name_plural': 'Transições de status dos posts',
                'db_table': 'post_status_transition',
                'ordering': ['-changed_at'],
            },
        ),
    ]
