# Generated by Django 6.0.2 on 2026-02-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [('setup', '0002_author_user_alter_author_id')]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Menu',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('title', models.CharField(max_length=100)),
                        ('slug', models.SlugField(max_length=100, unique=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'menu',
                        'ordering': ['title'],
                    },
                ),
                migrations.CreateModel(
                    name='Redirect',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('old_path', models.CharField(max_length=200, unique=True)),
                        ('new_path', models.CharField(max_length=200)),
                        ('url_type', models.CharField(max_length=20)),
                        ('is_active', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'redirect',
                        'ordering': ['-id'],
                    },
                ),
                migrations.CreateModel(
                    name='MenuItem',
                    fields=[
                        (
                            'id',
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        ('label', models.CharField(max_length=100)),
                        ('url', models.CharField(max_length=200)),
                        ('order', models.IntegerField()),
                        ('target', models.CharField(blank=True, max_length=20, null=True)),
                        ('is_active', models.BooleanField(default=True)),
                        (
                            'menu',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='navigation.menu',
                            ),
                        ),
                        (
                            'parent',
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name='children',
                                to='navigation.menuitem',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'menu_item',
                        'ordering': ['order'],
                    },
                ),
            ],
            database_operations=[],
        )
    ]
