# Generated by Django 6.0.2 on 2026-02-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title'], 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['order'], 'verbose_name_plural': 'Itens de menu'},
        ),
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Redirecionamentos'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='target',
            field=models.CharField(blank=True, choices=[('_self', 'Mesma aba'), ('_blank', 'Nova aba'), ('_parent', 'Janela pai'), ('_top', 'Janela topo')], default='_self', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='url_type',
            field=models.CharField(choices=[('permanent', '301 Permanente'), ('temporary', '302 Temporario')], default='permanent', max_length=20),
        ),
    ]
