# Generated by Django 6.0.2 on 2026-02-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_alter_menu_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='url_type',
            field=models.CharField(choices=[('permanent', '301 Permanente'), ('temporary', '302 Temporário')], default='permanent', max_length=20),
        ),
    ]
